Bump to v2.0.2 TPT1SFIV3
Signed-off-by: Pedrozzz0 <guitopzika26@gmail.com>

diff --git a/ktsrmenu b/ktsrmenu
--- a/ktsrmenu
+++ b/ktsrmenu
@@ -1,8 +1,46 @@
 #!/system/bin/sh
 # KTSR by Pedro (pedrozzz0 @ GitHub)
+# Credits: veez21
 # If you wanna use it as part of your project, please maintain the credits to it respective's author(s).
 
-MODPATH=/data/adb/modules/KTSR
+# Magisk Module ID **
+ID="KTSR"
+
+# Detect root
+_name=$(basename $0)
+ls /data >/dev/null 2>&1 || { echo "[!] $ID needs to run as root"; echo "type 'su' then '$_name'"; exit 1; }
+
+# Import magisk util_functions.sh
+[[ -f /data/adb/magisk/util_functions.sh ]] && . /data/adb/magisk/util_functions.sh || { echo "[!] util_functions.sh not detected"; exit 1; }
+
+# Magisk Mod Directory
+[[ -d "/sbin/.magisk" ]] && MOUNTPATH="/sbin/.magisk/modules" || MOUNTPATH="$(find /dev -mindepth 2 -maxdepth 2 -type d -name ".magisk")/modules"
+MODDIR="$MOUNTPATH/$ID"
+[[ ! -d $MODDIR ]] && { echo "[!] Module not detected"; exit 1; }
+
+# Set path to your busybox if applicable
+_bb=
+
+# Load mod-util.sh
+. $MODDIR/mod-util.sh || exit $?
+
+# Set Log Files
+mount -o remount,rw /cache 2>/dev/null
+mount -o rw,remount /cache 2>/dev/null
+# > Logs should go in this file
+LOG=/data/local/tmp/$ID.log
+oldLOG=/data/local/tmp/$ID-old.log
+# > Verbose output goes here
+VERLOG=/data/local/tmp/$ID-verbose.log
+oldVERLOG=/data/local/tmp/$ID-verbose-old.log
+stdoutLOG=$MODDIR/logs/$ID-STDOUT.log
+oldstdoutLOG=$MODDIR/logs/$ID-STDOUT-old.log
+
+# Start Logging verbosely
+mv -f $VERLOG $oldVERLOG 2>/dev/null; mv -f $LOG $oldLOG 2>/dev/null; mv -f $stdoutLOG $oldstdoutLOG 2>/dev/null
+# exec 3>&1
+# exec 1>$stdoutLOG
+set -x 2>$VERLOG
 
 kts_mode=$(getprop persist.kingtweaks.mode)
  	
@@ -29,20 +67,23 @@ kts_profile=Gaming
 elif [[ "$kts_mode" == "6" ]]
 then
 kts_profile=Latency
+
+else
+kts_profile=Unknown
 fi
 
 if [[ "$(settings get global low_power)" == "1" ]]; then
-low_power=Activated
+low_power_mode=Enabled
 
 else
-low_power=Deactivated
+low_power_mode=Disabled
 fi
 
-if [[ "$(cmd netpolicy get restrict-background | awk '{print $4}')" == "disabled" ]]; then
-data_saver=Disabled
+if [[ "$(cmd netpolicy get restrict-background | awk '{print $4}')" == "enabled" ]]; then
+data_saver=Enabled
 
 else
-data_saver=Enabled
+data_saver=Disabled
 fi
 
 if [[ "$(settings get secure location_providers_allowed)" == "" ]]; then
@@ -53,14 +94,13 @@ loc_mode_pwr_saving=Disabled
 fi
 
 if [[ "$(getprop init.svc.thermal-engine)" == "running" ]] || [[ "$(getprop init.svc.mi_thermald)" == "running" ]] || [[ "$(getprop init.svc.thermald)" == "running" ]] || [[ "$(getprop init.svc.thermalservice)" == "running" ]]; then
-thermal=On
+ts=On
 
 elif [[ "$(getprop init.svc.thermal-engine)" == "stopped" ]] || [[ "$(getprop init.svc.mi_thermald)" == "stopped" ]] || [[ "$(getprop init.svc.thermald)" == "stopped" ]] || [[ "$(getprop init.svc.thermalservice)" == "stopped" ]]; then
-thermal=Off
-fi
+ts=Off
 
-if [[ -z "$thermal" ]]; then
-thermal=Unknown
+else
+ts=Unknown
 fi
 
 menu() {
@@ -70,10 +110,10 @@ echo "******************************************"
 echo "* KTSR (Alt.) Profile Controller & Misc. *"
 echo "******************************************"
 echo ""
-echo "[*] Profile active: $kts_profile"
+echo "[*] Current Profile: ${G}$kts_profile${N}"
 echo ""
 sleep 1.5
-echo "[*] Thermal state: $thermal"
+echo "[*] Thermal: ${B}$thermal${N}"
 echo ""
 sleep 1.3
 echo "[*] Available profiles: "
@@ -82,16 +122,16 @@ sleep 1.2
 echo "[1] Automatic: Change your profile automatically based on specific circumstances and do additional tweaking for a better user-experience."
 echo ""
 sleep 2
-echo "[2] Battery: Reduce power draw to less battery drain and energetic comsumption, ensuring a juicy battery life."
+echo "${B}[2] Battery: Reduce power draw to less battery drain and energetic comsumption, ensuring a juicy battery life.${N}"
 echo ""
 sleep 1.5
-echo "[3] Balanced: Balanced between battery life and performance, perfect to be used as daily driver."
+echo "${G}[3] Balanced: Balanced between battery life and performance, perfect to be used as daily driver.${N}"
 echo ""
 sleep 2
-echo "[4] Extreme: Tweaks both CPU / GPU and more for less throttling, maintaining a consistent performance. May drain more battery also. Recommended to benchmarking / heavy apps."
+echo "${Y}[4] Extreme: Tweaks both CPU / GPU and more for less throttling, maintaining a consistent performance. May drain more battery also. Recommended to benchmarking / heavy apps.${N}"
 echo ""
 sleep 2.5
-echo "[5] Gaming: Recommended to gamers who want the best performance possible while playing, with almost zero throttling, tweaks both CPU / GPU and more to achieve it, will probably drain a lot of battery life."
+echo "${R}[5] Gaming: Recommended to gamers who want the best performance possible while playing, with almost zero throttling, tweaks both CPU / GPU and many other settings, will probably drain a lot of battery life.${N}"
 echo ""
 sleep 3.5
 echo "[6] Latency: Recommended to users who want really silky / smooth UI"
@@ -103,122 +143,122 @@ sleep 1.8
 echo "[7] Optimize apps package"
 echo ""
 sleep 1.6
-echo "[8] Optimize databases"
-echo ""
-sleep 1.4
-if [[ "$low_power" == "Deactivated" ]]; then
-echo "[9] Enable low power mode"
+if [[ "$low_power_mode" == "Disabled" ]]; then
+echo "[8] Enable low power mode"
 echo ""
 sleep 1.6
 else
-echo "[10] Disable low power mode"
+echo "[9] Disable low power mode"
 echo ""
 sleep 1.4
 fi
 if [[ "$data_saver" == "Disabled" ]]; then
-echo "[11] Enable data saver"
+echo "[10] Enable data saver"
 echo ""
 sleep 1.4
 else
-echo "[12] Disable data saver"
+echo "[11] Disable data saver"
 echo ""
 sleep 1.6
 fi
-if [[ "$loc_mode_pwr_saving" == "Enabled" ]]; then
-echo "[13] Enable power-saving location mode"
+if [[ "$loc_mode_pwr_saving" == "Disabled" ]]; then
+echo "[12] Enable power-saving location mode"
 echo ""
 sleep 1.7
 else
-echo "[14] Disable power-saving location mode"
+echo "[13] Disable power-saving location mode"
 echo ""
 sleep 1.9
 fi
-echo "[15] Clean trash files, E.G: System logs, debug logs, etc."
+echo "[14] Clean trash files, E.G: System logs, debug logs, etc."
 echo ""
 sleep 2.3
-echo "[16] Access our telegram group"
+echo "[15] Access our telegram group"
 echo ""
 sleep 1.6
-echo "[17] FKM updater script"
+echo "[16] FKM updater script"
 echo ""
 sleep 1.4
-echo "[18] Kill background apps"
+echo "[17] Kill background apps"
 echo ""
 sleep 1.3
-echo "[19] Update scripts"
-echo ""
-sleep 1.1
-if [[ "$thermal" == "On" ]]; then
-echo "[20] Disable thermal"
+if [[ "$ts" == "On" ]]; then
+echo "${B}[18] Disable thermal${N}"
 echo ""
 sleep 1
-elif [[ "$thermal" == "Off" ]]; then
-echo "[21] Enable thermal"
+elif [[ "$ts" == "Off" ]]; then
+echo "${B}[19] Enable thermal${N}"
 echo "" 
 sleep 1
 fi
-echo "[0] Exit"
+echo "${R}[0] Exit${N}"
 echo ""
 sleep 0.9
-echo -n "[*] Select the desired option: "
+echo -n "${Y}[*] Select the desired option:${N} "
 read -r option
 		case $option in
 			"1")
-				echo "Applying profile..."
-				setprop persist.kingtweaks.mode 1
+				echo "${B}Applying profile...${N}"
+				setprop persist.kingtweaks.mode "1" 2>/dev/null
+                echo "${G}Done!${N}"
 				;;
 				
 						"2")
-						echo "Applying profile..."
-						setprop persist.kingtweaks.mode 2
-						;;
+						echo "${B}Applying profile...${N}"
+						setprop persist.kingtweaks.mode "2" 2>/dev/null
+						echo "${G}Done!"
+                        ;;
 						
 						"3")
-						echo "Applying profile..."
-						setprop persist.kingtweaks.mode 3
+						echo "${B}Applying profile...${N}"
+						setprop persist.kingtweaks.mode "3" 2>/dev/null
+                        echo "${G}Done!${N}"
 						;;
 						
 						"4")
-						echo "Applying profile..."
-						setprop persist.kingtweaks.mode 4
-						;;
+						echo "${B}Applying profile...${N}"
+						setprop persist.kingtweaks.mode "4" 2>/dev/null
+						echo "${G}Done!${N}"
+                        ;;
 						
 						"5")
-						echo "Applying profile..."
-						setprop persist.kingtweaks.mode 5
-						;;
+						echo "${B}Applying profile...${N}"
+						setprop persist.kingtweaks.mode "5" 2>/dev/null
+						echo "${G}Done!${N}"
+                        ;;
 						
 						"6")
-						echo "Applying profile..."
-						setprop persist.kingtweaks.mode 6
-						;;
+						echo "${B}Applying profile...${N}"
+						setprop persist.kingtweaks.mode "6" 2>/dev/null
+						echo "${G}Done!${N}"
+                        ;;
 						
 						"7")
-						echo "Optimizing..."
-						cmd package bg-dexopt-job; echo "Done!"
+						echo "${B}Optimizing packages...${N}"
+						cmd package bg-dexopt-job
 						;;
 						
 						"8")
 						if [[ $(find /system -name "sqlite3" -type f) ]]; then
-						echo "[*] Optimizing..."
+						echo "${B}Optimizing databases...${N}"
 						for i in $(find /d* -iname "*.db"); do
-                        sqlite3 "$i" 'VACUUM;'
+                        sqlite3 "$i" 'VACUUM;' 2>/dev/null
                         resVac=$?
                         if [[ $resVac == 0 ]]; then
                         resVac="SUCCESS"
                         else
                         resVac="FAILED(ERRCODE)-$resVac"
                         fi
-                        sqlite3 "$i" 'REINDEX;'
+                        sqlite3 "$i" 'REINDEX;' 2>/dev/null
                         resIndex=$?
                         if [[ $resIndex == 0 ]]; then
                         resIndex="SUCCESS"
                         else
                         resIndex="FAILED(ERRCODE)-$resIndex"
                         fi
-                        sqlite3 "$i" 'ANALYZE;'
+                        sqlite3 "$i" 'ANALYZE;' 2>/dev/null
                         resAnlz=$?
-                        if [ $resAnlz == 0 ]; then
+                        if [[ $resAnlz == 0 ]]; then
                         resAnlz="SUCCESS"
                         else
                         resAnlz="FAILED(ERRCODE)-$resAnlz"
@@ -226,48 +266,48 @@ read -r option
                         echo -e "Database $i: VACUUM=$resVac REINDEX=$resIndex ANALYZE=$resAnlz" >> /sdcard/KTSR/dbopt.log
                         done
 						else
-						echo "[!] SQLite not found, aborting..."
+						echo "${R}[!] SQLite not found, aborting...${N}"
                         fi
                         ;;
 						
                         "9")
                         settings put global low_power 1
-                        echo "Done!"
+                        echo "${G}Done!${N}"
                         ;;
                         
                         "10")
                         settings put global low_power 0
-                        echo "Done!"
+                        echo "${G}Done!${N}"
                         ;;
                         
                         "11")
                         cmd netpolicy set restrict-background true
-                        echo "Done!"
+                        echo "${G}Done!${N}"
                         ;;
                         
                         "12")
                         cmd netpolicy set restrict-background false
-                        echo "Done!"
+                        echo "${G}Done!${N}"
                         ;;
                         
                         "13")
-                        echo "Applying settings..."
+                        echo "${B}Applying settings...${N}"
                         settings put secure location_mode "0"
                         settings put secure location_providers_allowed ""
                         echo "0" > "/sys/module/service_locator/parameters/enable"
-                        echo "Done!"
+                        echo "${G}Done!${N}"
                         ;;
                         
                         "14")
                         settings put secure location_providers_allowed "gps,network"
                         echo "1" > "/sys/module/service_locator/parameters/enable"
-                        echo "Done!"
+                        echo "${G}Done!${N}"
                         ;;
                         
                         "15")
-                        echo "Cleaning debug logs & system trash..."
+                        echo "${B}Cleaning debug logs and system trash...${N}"
                         cleantrash
-                        echo "Done!"
+                        echo "${G}Done!${N}"
                         ;;
                         
 						"16")
@@ -280,46 +320,36 @@ read -r option
 						;;
 						
 						"18")
-						echo "Killing all background apps..."
+						echo "${B}Killing all background apps...${N}"
 						am kill-all
-						sleep 1.8
-						echo "Done!"
-						;;
-						
-						"19")
-						echo "Updating scripts..."
-						wget -O "$MODPATH"/system/bin/kingtweaks "https://raw.githubusercontent.com/pedrozzz0/King-Tweaks/master/kingtweaks"
-						wget -O "$MODPATH"/system/bin/kingauto "https://raw.githubusercontent.com/pedrozzz0/King-Tweaks/master/kingauto"
-						wget -O "$MODPATH"/libs/libktsr.sh "https://raw.githubusercontent.com/pedrozzz0/King-Tweaks/master/libktsr.sh"
-						wget -O "$MODPATH"/system/bin/ktsrmenu "https://raw.githubusercontent.com/pedrozzz0/King-Tweaks/master/ktsrmenu"
-						wget -O "$MODPATH"/system/bin/cleantrash "https://raw.githubusercontent.com/pedrozzz0/King-Tweaks/master/cleantrash"
-						echo "Done! Reboot to the effects be applied."
+						sleep 2
+						echo "${G}Done!${N}"
 						;;
                         
 						"20")
-						echo "Disabling thermal..."
-						stop thermald
-						stop thermalservice
-						stop mi_thermald
-						stop thermal-engine
-						echo "Done!"
+						echo "${B}Disabling thermal...${N}"
+						stop thermald 2>/dev/null
+						stop thermalservice 2>/dev/null
+						stop mi_thermald 2>/dev/null
+						stop thermal-engine 2>/dev/null
+						echo "${G}Done!${N}"
 						;;
 
 						"21")
-						echo "Enabling thermal..."
-						start thermald
-						start thermalservice
-						start mi_thermald
-						start thermal-engine
-						echo "Done!"
+						echo "${B}Enabling thermal...${N}"
+						start thermald 2>/dev/null
+						start thermalservice 2>/dev/null
+						start mi_thermald 2>/dev/null
+						start thermal-engine 2>/dev/null
+						echo "${G}Done!${N}"
 						;;
 						
 						"0")
-						echo "Hope that see ya soon! ;)"
+						echo "${G}Hope that see ya soon! ;)${N}"
 						;;
 						
 						*)
-						echo "[!] Unexpected response, aborting..."
+						echo "${R}[!] Unexpected response, aborting...${N}"
 						;;
 						esac
 						}
@@ -328,48 +358,52 @@ read -r option
 						menu
 						fi
 
-						usage() {
-							echo "Usage: ktsrmenu [-p <value corresponding to the profile (0-6)>] [-h <trigger this dialog>] [ -t <Disable thermal if enabled and vice-versa>"
-							echo "[1] Automatic"
-                            echo "[2] Battery"
-                            echo "[3] Balanced"
-                            echo "[4] Extreme"
-                            echo "[5] Gaming"
-                            echo "[6] Latency"
-							exit 1
-							}
+						help_me(){
+                        echo "$MODTITLE $VER($REL)"
+                        echo "by $AUTHOR"
+                        echo "Usage: $_name"
+                        echo "or: $_name [options]..."
+                        echo "Supported options:"
+                        echo "-p [profile] [value from 1 to 6] [change between profiles without the terminal GUI]"
+                        echo "-t [thermal] [enable / disable thermal services according to your actual state without the terminal GUI]"
+                        echo "-h [help] [show this message]"
+                        exit
+                        }
 						
 						while getopts ":p:th:" opt; do
-						[[ $# -gt 2 ]] && usage
+						[[ $# -gt 2 ]] && help_me
 						case "${opt}" in
 						
-						p) echo "Applying profile..."
-						setprop persist.kingtweaks.mode "$2"
-						;;
+						p) echo "${B}Applying profile...${N}"
+						setprop persist.kingtweaks.mode "$2" 2>/dev/null
+						echo "${G}Done!${N}"
+                        ;;
 						
 						t) if [[ $thermal == "On" ]]; then 
 						echo "Disabling thermal..."
-						stop thermald
-						stop thermalservice
-						stop mi_thermald
-						stop thermal-engine
-						echo "Done!"
+						stop thermald 2>/dev/null
+						stop thermalservice 2>/dev/null
+						stop mi_thermald 2>/dev/null
+						stop thermal-engine 2>/dev/null
+						echo "${G}Done!${N}"
 						elif [[ $thermal == "Off" ]]; then
-						echo "Enabling thermal..."
-						start thermald
-						start thermalservice
-						start mi_thermald
-						start thermal-engine
-						echo "Done!"
+						echo "${B}Enabling thermal...${N}"
+						start thermald 2>/dev/null
+						start thermalservice 2>/dev/null
+						start mi_thermald 2>/dev/null
+						start thermal-engine 2>/dev/null
+						echo "${G}Done!${N}"
 						else
-                        echo "[!] No valid thermal controllers found / Unknown thermal state. Aborting..."
+                        echo "${R}[!] No valid thermal controllers found / Unknown thermal state, aborting...${N}"
                         exit 1
 						fi
 						;;
 						
-						h | *) usage
+						h | *) help_me
 						;;
 						esac
                         done
 
                         shift $((OPTIND - 1))
+                        
+                        exit 0
