Some fixes and improvements to CLI
** Try to make it look better

** Improve current inputs with extended options like ktsrmenu --profile, --clear-ram, --help, --game

Signed-off-by: Pedrozzz0 <guitopzika26@gmail.com>

diff --git a/ktsrmenu b/ktsrmenu
--- a/ktsrmenu
+++ b/ktsrmenu
@@ -2,8 +2,9 @@
 # KTSR™ by Pedro (pedrozzz0 @ GitHub)
 # Credits: veez21
 # If you wanna use it as part of your project, please maintain the credits to it respective's author(s).
+# ToDo: Make it look less ugly
 
-# Magisk Module ID **
+# Magisk Module ID
 ID="KTSR"
 
 # Detect root
@@ -53,10 +54,6 @@ mv -f "$VERLOG" "$oldVERLOG" 2>/dev/null
 mv -f "$LOG" "$oldLOG" 2>/dev/null
 mv -f "$stdoutLOG" "$oldstdoutLOG" 2>/dev/null
 
-# exec 3>&1
-
-# exec 1>$stdoutLOG
-
 set -x 2>"$VERLOG"
 
 ktsr_prof=$(getprop persist.king.tweaks.prof)
@@ -81,27 +78,27 @@ sdk=$(getprop ro.build.version.sdk)
 menu() {
 	clear
 	echo ""
-	echo "${Y}************${N}"
-	echo "${Y}* KTSR CLI *${N}"
-	echo "${Y}************${N}"
+	echo "$Y*************************************$N"
+	echo "$Y* KTSR Command Line Interface (CLI) *$N"
+	echo "$Y*************************************$N"
 	echo ""
-	echo "${G}Ver: 1.6.3.5-r13${N}"
+	echo "${G}Version: 1.6.3.6-r14$N"
 	echo ""
-	echo "[*] Current Profile: ${G}$ktsr_prof_en${N}"
+	echo "$V[*] Current Profile:$N $G$ktsr_prof_en$N"
 	echo ""
-	echo "[*] Available profiles: "
+	echo "$Bl[*] Available profiles:$N "
 	echo ""
-	echo "${C}[1] Automatic: Change between profiles automatically based on user activity for a better user-experience.${N}"
+	echo "$C[1] Automatic: Change between profiles automatically based on user activity for a better user-experience and consistency.$N"
 	echo ""
-	echo "${B}[2] Battery: Reduce SOC power draw to less battery comsumption, ensuring a juicy battery life.${N}"
+	echo "$B[2] Battery: Reduce overall SOC power draw to less battery comsumption, ensuring a juicy battery life.$N"
 	echo ""
-	echo "${G}[3] Balanced: Balanced between battery life and performance, perfect to be used on day-to-day activities.${N}"
+	echo "$G[3] Balanced: Balanced between battery consumption and performance, perfect to be used on day-to-day activities.$N"
 	echo ""
-	echo "${Y}[4] Extreme: Tweaks both CPU / GPU for a consistent experience while dealing with heavy apps. May drain more battery life compared to Balanced / Latency.${N}"
+	echo "$Y[4] Extreme: Tweaks both CPU / GPU for a consistent experience while dealing with heavy apps. May consume more battery compared to Balanced / Latency.$N"
 	echo ""
-	echo "${R}[5] Gaming: Recommended to users who wants the best performance possible while playing, tweaking both CPU / GPU to it's max. May drain a lot of battery life.${N}"
+	echo "$R[5] Gaming: Recommended to users who wants the best performance possible while playing, tweaking both CPU / GPU to it's max. May consume a lot of battery.$N"
 	echo ""
-	echo "[6] Latency: Recommended to users who want really silky / smooth UI"
+	echo "$V[6] Latency: Recommended to users who want really silky / smooth UI.$N"
 	echo ""
 	echo "[*] Other misc options: "
 	echo ""
@@ -153,11 +150,11 @@ menu() {
 	}
 	echo "[21] Reset Refresh Rate config"
 	echo ""
-	echo "[22] Free RAM [ Balanced ] (Will only drop caches)."
+	echo "[22] Free RAM [Balanced] (Will only drop caches)."
 	echo ""
-	echo "[23] Free RAM [ Agressive ] (Will kill all background apps and drop caches)."
+	echo "[23] Free RAM [Agressive] (Will kill all background apps and drop caches)."
 	echo ""
-	echo "[24] Free RAM [ Extreme ] (Will kill all apps, and drop caches)."
+	echo "[24] Free RAM [Extreme] (Will kill all apps, and drop caches)."
 	echo ""
 	[[ -e "/sys/class/thermal/thermal_message/sconfig" ]] && [[ "$(cat /sys/class/thermal/thermal_message/sconfig)" != "2" ]] && {
 		echo "[25] Switch to dynamic thermal profile (May improve charging speed)"
@@ -190,54 +187,54 @@ menu() {
 	echo "[35] Set renderer to Skia Vulkan"
 	echo ""
 	}
-	echo "${R}[0] Exit${N}"
+	echo "$R[0] Exit$N"
 	echo ""
-	echo -n "${Y}[*] Select the desired option:${N} "
+	echo -n "$Y[*] Select the desired option:$N "
 	read -r option
 	case "$option" in
 		"1")
-			echo "${B}Applying profile...${N}"
+			echo "${B}Applying profile...$N"
 			setprop persist.king.tweaks.prof "1" 2>/dev/null
-			[[ $? == "0" ]] && echo "${G}[*] Done!${N}" || echo "${R}[!] Something went wrong!"
+			[[ $? == "0" ]] && echo "$G[*] Done!$N" || echo "$R[!] Something went wrong!$N"
 			sleep 2
 			menu
 			;;
 		"2")
-			echo "${B}Applying profile...${N}"
+			echo "${B}Applying profile...$N"
 			setprop persist.king.tweaks.prof "2" 2>/dev/null
-			[[ $? == "0" ]] && echo "${G}[*] Done!${N}" || echo "${R}[!] Something went wrong!"
+			[[ $? == "0" ]] && echo "$G[*] Done!$N" || echo "$R[!] Something went wrong!$N"
 			sleep 2
 			menu
 			;;
 		"3")
-			echo "${B}Applying profile...${N}"
+			echo "${B}Applying profile...$N"
 			setprop persist.king.tweaks.prof "3" 2>/dev/null
-			[[ $? == "0" ]] && echo "${G}[*] Done!${N}" || echo "${R}[!] Something went wrong!"
+			[[ $? == "0" ]] && echo "$G[*] Done!$N" || echo "$R[!] Something went wrong!$N"
 			menu
 			;;
 		"4")
-			echo "${B}Applying profile...${N}"
+			echo "${B}Applying profile...$N"
 			setprop persist.king.tweaks.prof "4" 2>/dev/null
-			[[ $? == "0" ]] && echo "${G}[*] Done!${N}" || echo "${R}[!] Something went wrong!"
+			[[ $? == "0" ]] && echo "$G[*] Done!$N" || echo "$R[!] Something went wrong!$N"
 			sleep 2
 			menu
 			;;
 		"5")
-			echo "${B}Applying profile...${N}"
+			echo "${B}Applying profile...$N"
 			setprop persist.king.tweaks.prof "5" 2>/dev/null
-			[[ $? == "0" ]] && echo "${G}[*] Done!${N}" || echo "${R}[!] Something went wrong!"
+			[[ $? == "0" ]] && echo "$G[*] Done!$N" || echo "$R[!] Something went wrong!$N"
 			sleep 2
 			menu
 			;;
 		"6")
-			echo "${B}Applying profile...${N}"
+			echo "${B}Applying profile...$N"
 			setprop persist.king.tweaks.prof "6" 2>/dev/null
-			[[ $? == "0" ]] && echo "${G}[*] Done!${N}" || echo "${R}[!] Something went wrong!"
+			[[ $? == "0" ]] && echo "$G[*] Done!$N" || echo "$R[!] Something went wrong!$N"
 			sleep 2
 			menu
 			;;
 		"7")
-			echo "${B}Optimizing packages...${N}"
+			echo "${B}Optimizing packages, this may take some time...$N"
 			pm compile -a -f --compile-layouts
 			cmd package bg-dexopt-job
 			sleep 2
@@ -250,7 +247,7 @@ menu() {
 			settings put global forced_app_standby_enabled 1 2>/dev/null
 			settings put global app_auto_restriction_enabled true 2>/dev/null
 			settings put global forced_app_standby_for_small_battery_enabled 1 2>/dev/null
-			[[ $? == "0" ]] && echo "${G}[*] Done!${N}" || echo "${R}[!] Something went wrong!"
+			[[ $? == "0" ]] && echo "$G[*] Done!$N" || echo "$R[!] Something went wrong!$N"
 			sleep 2
 			menu
 			;;
@@ -267,19 +264,19 @@ menu() {
 			settings reset global app_auto_restriction_enabled 2>/dev/null
 			settings put global forced_app_standby_for_small_battery_enabled 0 2>/dev/null
 			settings reset global forced_app_standby_for_small_battery_enabled 1 2>/dev/null
-			[[ $? == "0" ]] && echo "${G}[*] Done!${N}" || echo "${R}[!] Something went wrong!"
+			[[ $? == "0" ]] && echo "$G[*] Done!$N" || echo "$R[!] Something went wrong!$N"
 			sleep 2
 			menu
 			;;
 		"10")
 			cmd netpolicy set restrict-background true 2>/dev/null
-			[[ $? == "0" ]] && echo "${G}[*] Done!${N}" || echo "${R}[!] Something went wrong!"
+			[[ $? == "0" ]] && echo "$G[*] Done!$N" || echo "$R[!] Something went wrong!$N"
 			sleep 2
 			menu
 			;;
 		"11")
 			cmd netpolicy set restrict-background false 2>/dev/null
-			[[ $? == "0" ]] && echo "${G}[*] Done!${N}" || echo "${R}[!] Something went wrong!"
+			[[ $? == "0" ]] && echo "$G[*] Done!$N" || echo "$R[!] Something went wrong!$N"
 			sleep 2
 			menu
 			;;
@@ -287,20 +284,20 @@ menu() {
 			echo "${B}Applying settings...${N}"
 			settings put secure location_mode "0" 2>/dev/null
 			settings put global assisted_gps_enabled "0" 2>/dev/null
-			[[ $? == "0" ]] && echo "${G}[*] Done!${N}" || echo "${R}[!] Something went wrong!"
+			[[ $? == "0" ]] && echo "$G[*] Done!$N" || echo "$R[!] Something went wrong!"
 			sleep 2
 			menu
 			;;
 		"13")
 			settings put global assisted_gps_enabled "1" 2>/dev/null
-			[[ $? == "0" ]] && echo "${G}[*] Done!${N}" || echo "${R}[!] Something went wrong!"
+			[[ $? == "0" ]] && echo "$G[*] Done!$N" || echo "$R[!] Something went wrong!"
 			sleep 2
 			menu
 			;;
 		"14")
-			echo "${B}Cleaning debug logs and system trash...${N}"
+			echo "${B}Cleaning debug logs and system trash...$N"
 			cleantrash 2>/dev/null
-			echo "${G}[*] Done!${N}"
+			echo "$G[*] Done!$N"
 			sleep 2
 			menu
 			;;
@@ -310,13 +307,13 @@ menu() {
 			;;
 		"16")
 			[[ -e "/sys/module/mdss_mdp/parameters/custom_hz" ]] && [[ "$(grep -Eo '[0-9]' /sys/module/mdss_mdp/parameters/custom_hz 2>/dev/null)" ]] && echo "50" >"/sys/module/mdss_mdp/parameters/custom_hz" || echo "Y" >"/sys/module/mdss_mdp/parameters/custom_hz"
-			[[ $? == "0" ]] && echo "${G}[*] Done!${N}" || echo "${R}[!] Something went wrong!"
+			[[ $? == "0" ]] && echo "$G[*] Done!$N" || echo "$R[!] Something went wrong!$N"
 			sleep 2
 			menu
 			;;
 		"17")
 			[[ -e "/sys/module/mdss_mdp/parameters/custom_hz" ]] && [[ "$(grep -Eo '[0-9]' /sys/module/mdss_mdp/parameters/custom_hz 2>/dev/null)" ]] && echo "55" >"/sys/module/mdss_mdp/parameters/custom_hz"
-			[[ $? == "0" ]] && echo "${G}[*] Done!${N}" || echo "${R}[!] Something went wrong!"
+			[[ $? == "0" ]] && echo "$G[*] Done!$N" || echo "$R[!] Something went wrong!$N"
 			sleep 2
 			menu
 			;;
@@ -328,7 +325,7 @@ menu() {
 			settings put global oneplus_screen_refresh_rate 1 2>/dev/null
 			settings put secure coloros_screen_refresh_rate 2 2>/dev/null
 			service call SurfaceFlinger 1035 i32 1 >/dev/null 2>&1
-			[[ $? == "0" ]] && echo "${G}[*] Done!${N}" || echo "${R}[!] Something went wrong!"
+			[[ $? == "0" ]] && echo "$G[*] Done!$N" || echo "$R[!] Something went wrong!$N"
 			sleep 2
 			menu
 			;;
@@ -339,7 +336,7 @@ menu() {
 			settings put global oneplus_screen_refresh_rate 0 2>/dev/null
 			settings put secure coloros_screen_refresh_rate 1 2>/dev/null
 			service call SurfaceFlinger 1035 i32 0 >/dev/null 2>&1
-			[[ $? == "0" ]] && echo "${G}[*] Done!${N}" || echo "${R}[!] Something went wrong!"
+			[[ $? == "0" ]] && echo "$G[*] Done!$N" || echo "$R[!] Something went wrong!$N"
 			sleep 2
 			menu
 			;;
@@ -349,7 +346,7 @@ menu() {
 			settings put system user_refresh_rate 120 2>/dev/null
 			settings put global oneplus_screen_refresh_rate 0 2>/dev/null
 			settings put secure coloros_screen_refresh_rate 3 2>/dev/null
-			[[ $? == "0" ]] && echo "${G}[*] Done!${N}" || echo "${R}[!] Something went wrong!"
+			[[ $? == "0" ]] && echo "$G[*] Done!$N" || echo "$R[!] Something went wrong!$N"
 			sleep 2
 			menu
 			;;
@@ -360,14 +357,14 @@ menu() {
 			settings reset global oneplus_screen_refresh_rate >/dev/null 2>&1
 			settings reset secure coloros_screen_refresh_rate >/dev/null 2>&1
 			service call SurfaceFlinger 1035 i32 1 >/dev/null 2>&1
-			[[ $? == "0" ]] && echo "${G}[*] Done!${N}" || echo "${R}[!] Something went wrong!"
+			[[ $? == "0" ]] && echo "$G[*] Done!$N" || echo "$R[!] Something went wrong!$N"
 			sleep 2
 			menu
 			;;
 		"22")
 			sync
 			echo "3" >"/proc/sys/vm/drop_caches"
-			[[ $? == "0" ]] && echo "${G}[*] Done!${N}" || echo "${R}[!] Something went wrong!"
+			[[ $? == "0" ]] && echo "$G[*] Done!$N" || echo "$R[!] Something went wrong!$N"
 			sleep 4
 			menu
 			;;
@@ -375,7 +372,7 @@ menu() {
 			sync
 			echo "3" >"/proc/sys/vm/drop_caches"
 			am kill-all
-			[[ $? == "0" ]] && echo "${G}[*] Done!${N}" || echo "${R}[!] Something went wrong!"
+			[[ $? == "0" ]] && echo "$G[*] Done!$N" || echo "$R[!] Something went wrong!$N"
 			sleep 4
 			menu
 			;;
@@ -387,19 +384,19 @@ menu() {
 			while IFS= read -r pkg_nm; do
 				[[ "$pkg_nm" != "com.termux" ]] && [[ "$pkg_nm" != "jackpal.androidterm" ]] && [[ "$pkg_nm" != "yarolegovich.materialterminal" ]] && [[ "$pkg_nm" != "com.google.android.inputmethod.latin" ]] && [[ "$pkg_nm" != "com.termoneplus" ]] && [[ "$pkg_nm" != "com.pittvandewitt.viperfx" ]] && [[ "$pkg_nm" != "com.topjohnwu.magisk" ]] && [[ "$pkg_nm" != "ridmik.keyboard" ]] && [[ "$pkg_nm" != "com.maxmpz.equalizer" ]] && [[ "$pkg_nm" != "com.miui.screenrecorder" ]] && am force-stop "$pkg_nm"
 			done <<<"$(pm list packages -e -3 | grep package | cut -f 2 -d ":")"
-			echo "${G}Done!${N}"
+			echo "${G}Done!$N"
 			sleep 2
 			menu
 			;;
 		"25")
 			echo "2" >"/sys/class/thermal/thermal_message/sconfig" 2>/dev/null
-			[[ $? == "0" ]] && echo "${G}[*] Done!${N}" || echo "${R}[!] Something went wrong!"
+			[[[ $? == "0" ]] && echo "$G[*] Done!$N" || echo "$R[!] Something went wrong!$N"
 			sleep 2
 			menu
 			;;
 		"26")
 			echo "0" >"/sys/class/thermal/thermal_message/sconfig" 2>/dev/null
-			[[ $? == "0" ]] && echo "${G}[*] Done!${N}" || echo "${R}[!] Something went wrong!"
+			[[ $? == "0" ]] && echo "$G[*] Done!$N" || echo "$R[!] Something went wrong!$N"
 			sleep 2
 			menu
 			;;
@@ -411,7 +408,7 @@ menu() {
 			rm -rf /data/system/battery-history 2>/dev/null
 			rm -rf /data/vendor/charge_logger 2>/dev/null
 			rm -rf /data/charge_logger 2>/dev/null
-			echo "${G}[*] Done!${N}"
+			echo "${G}[*] Done!$N"
 			sleep 2
 			menu
 			;;
@@ -419,15 +416,15 @@ menu() {
 			am start -a android.intent.action.VIEW -d https://github.com/pedrozzz0/King-Tweaks/wiki/KTW
 			;;
 		"29")
-			echo "Values supported: [0.3-0.9]"
-			echo "Lower means more downscaled / lower resolution"
+			echo "Value range supported: [0.3-0.9]"
+			echo "A lower value means lower resolution"
 			echo "[*] Enter a value from the supported range: "
 			read -r lvl
 			echo "E.G: [com.android.camera]"
 			echo "[*] Enter a package name:"
 			read -r pkg
 			cmd game downscale "$lvl" "$pkg" 2>/dev/null
-			[[ $? == "0" ]] && echo "${G}[*] Done!${N}" || echo "${R}[!] Something went wrong!"
+			[[ $? == "0" ]] && echo "$G[*] Done!$N" || echo "$R[!] Something went wrong!$N"
 			sleep 2
 			menu
 			;;
@@ -436,7 +433,7 @@ menu() {
 			echo "[*] Enter a package name:"
 			read -r pkg
 			cmd game downscale disable "$pkg" 2>/dev/null
-			[[ $? == "0" ]] && echo "${G}[*] Done!${N}" || echo "${R}[!] Something went wrong!"
+			[[ $? == "0" ]] && echo "$G[*] Done!$N" || echo "$R[!] Something went wrong!$N"
 			sleep 2
 			menu
 			;;
@@ -450,7 +447,7 @@ menu() {
 			pm enable com.android.vending 2>/dev/null
 			pm enable com.google.android.play.games 2>/dev/null
 			pm enable com.google.android.syncadapters.contacts 2>/dev/null
-			echo "${G}[*] Done!${N}"
+			echo "${G}[*] Done!$N"
 			sleep 2
 			menu
 			;;
@@ -464,7 +461,7 @@ menu() {
 			pm disable com.android.vending 2>/dev/null
 			pm disable com.google.android.play.games 2>/dev/null
 			pm disable com.google.android.syncadapters.contacts 2>/dev/null
-			echo "${G}[*] Done!${N}"
+			echo "${G}[*] Done!$N"
 			sleep 2
 			menu
 			;;
@@ -474,11 +471,11 @@ menu() {
 			sed -i 's/debug.hwui.renderer.*/debug.hwui.renderer=opengl/' "$MODDIR/system.prop"
 			sed -i 's/ro.hwui.use_vulkan.*/ro.hwui.use_vulkan=/' "$MODDIR/system.prop"
 			sed -i '/debug.renderengine.backend/s/.*/debug.renderengine.backend=skiaglthreaded/' "$MODDIR/system.prop"
-			echo "${G}[*] Done!${N}"
+			echo "${G}[*] Done!$N"
 			sleep 2
 			menu
 			} || {
-			echo "[!] Android version not supported!"
+			echo "$R[!] Android version not supported!$N"
 			sleep 2
 			menu
 			}
@@ -489,11 +486,11 @@ menu() {
 			sed -i 's/debug.hwui.renderer.*/debug.hwui.renderer=skiagl/' "$MODDIR/system.prop"
 			sed -i 's/ro.hwui.use_vulkan.*/ro.hwui.use_vulkan=/' "$MODDIR/system.prop"
 			sed -i '/debug.renderengine.backend/s/.*/debug.renderengine.backend=skiaglthreaded/' "$MODDIR/system.prop"
-			echo "${G}[*] Done!${N}"
+			echo "${G}[*] Done!$N"
 			sleep 2
 			menu
 			} || {
-			echo "[!] Android version not supported!"
+			echo "$R[!] Android version not supported!$N"
 			sleep 2
 			menu
 			}
@@ -504,20 +501,20 @@ menu() {
 			sed -i 's/debug.hwui.renderer.*/debug.hwui.renderer=/' "$MODDIR/system.prop"
 			sed -i 's/ro.hwui.use_vulkan.*/ro.hwui.use_vulkan=true/' "$MODDIR/system.prop"
 			sed -i '/debug.renderengine.backend/s/.*/debug.renderengine.backend=skiaglthreaded/' "$MODDIR/system.prop"
-			echo "${G}[*] Done!${N}"
+			echo "${G}[*] Done!$N"
 			sleep 2
 			menu
 			} || {
-			echo "[!] Android version not supported!"
+			echo "$R[!] Android version not supported!$N"
 			sleep 2
 			menu
 			}
 			;;
 		"0")
-			echo "${G}Hope that see ya soon! ;)${N}"
+			echo "${G}Hope that see ya soon! ;)$N"
 			;;
 		*)
-			abort "${R}[!] Unexpected response, aborting...${N}"
+			abort "$R[!] Unexpected response, aborting...$N"
 			;;
 	esac
 }
@@ -526,27 +523,27 @@ menu() {
 
 help_me() {
 	echo "$MODTITLE $VER($REL)
-	by $AUTHOR
-	Usage: $_name
-	or: $_name [options]...
-	Telegram group: https://t.me/kingprojectz
-	Supported options:
-	-p [profile] [1-6] [change between profiles without opening the terminal GUI]
-	-f [free ram] [1-3] [Higher value means more agressive]
-	-h [help] [show this message]
-	-g [game] [enable DND and disable automatic rotation/brightness]"
+by $AUTHOR
+Usage: $_name
+or: $_name [options]...
+Telegram group: https://t.me/kingprojectz
+Supported options:
+-p --profile [1-6] [change between profiles without opening the terminal GUI]
+-f --clear-ram [1-3] [Higher value means more agressive cleaning]
+-h --help [show this message]
+-g --game [enable DND and disable automatic rotation/brightness]"
 	am start -a android.intent.action.VIEW -d https://github.com/pedrozzz0/King-Tweaks/wiki/KTW
 	exit
 }
 
 while getopts ":p:f:h:g:" opt; do
 	case "$opt" in
-		p)
+		p | --profile)
 			echo "${B}[*] Applying profile...${N}"
 			setprop persist.king.tweaks.prof "$2" 2>/dev/null
 			echo "${G}[*] Done!${N}"
 			;;
-		f)
+		f | --clear-ram)
 			[[ "$2" == "1" ]] && {
 				sync
 				echo "3" >"/proc/sys/vm/drop_caches"
@@ -570,17 +567,17 @@ while getopts ":p:f:h:g:" opt; do
 				sleep 2
 			}
 			;;
-		g)
+		g | --game)
 			cmd notification set_dnd priority >/dev/null 2>&1
 			settings put system screen_brightness_mode 0 >/dev/null 2>&1
-			wm set-user-rotation lock /dev/null 2>&1
-			wm user-rotation lock /dev/null 2>&1
+			wm set-user-rotation lock >/dev/null 2>&1
+			wm user-rotation lock >/dev/null 2>&1
 			sync
 			echo "3" >"/proc/sys/vm/drop_caches"
 			am kill-all
 			echo "${G}[*] Done!${N}"
 			;;
-		h | *)
+		h | --help)
 			help_me
 			;;
 	esac
