Import all options to flags
Signed-off-by: pedrozzz0 <guitopzika26@gmail.com>

diff --git a/ktsrmenu b/ktsrmenu
--- a/ktsrmenu
+++ b/ktsrmenu
@@ -281,13 +281,77 @@ read -r option
 						;;
 						
 						o) optslct="$OPTARG"
-						if [[ "$optslct" -eq "7" ]]; then 
-						cmd package bg-dexopt-job
-                        fi
 						;;
 						esac
                         done
                         
+                        if [[ "$optslct" -eq "7" ]]; then 
+						cmd package bg-dexopt-job
+                        
+                        elif [[ "$optslct" -eq "8" ]]; then
+                        if [[ $(find /system -name "sqlite3" -type f) ]]; then
+						echo "[*] Optimizing..."
+						for i in $(find /d* -iname "*.db"); do
+                        sqlite3 "$i" 'VACUUM;'
+                        resVac=$?
+                        if [[ $resVac == 0 ]]; then
+                        resVac="SUCCESS"
+                        else
+                        resVac="FAILED(ERRCODE)-$resVac"
+                        fi
+                        sqlite3 "$i" 'REINDEX;'
+                        resIndex=$?
+                        if [[ $resIndex == 0 ]]; then
+                        resIndex="SUCCESS"
+                        else
+                        resIndex="FAILED(ERRCODE)-$resIndex"
+                        fi
+                        sqlite3 $i 'ANALYZE;'
+                        resAnlz=$?
+                        if [ $resAnlz == 0 ]; then
+                        resAnlz="SUCCESS"
+                        else
+                        resAnlz="FAILED(ERRCODE)-$resAnlz"
+                        fi
+                        echo -e "Database $i: VACUUM=$resVac REINDEX=$resIndex ANALYZE=$resAnlz" >> /sdcard/KTSR/dbopt.log
+                        done
+						else
+						echo "[!] SQLite not found, aborting..."
+                        fi
+                        
+                        elif [[ "$optslct" -eq "9" ]]; then
+                        settings put global low_power 1
+                        
+                        elif [[ "$optslct" -eq "10" ]]; then
+                        settings put global low_power 0
+                        
+                        elif [[ "$optslct" -eq "11" ]]; then
+                        cmd netpolicy set restrict-background true
+                        
+                        elif [[ "$optslct" -eq "12" ]]; then
+                        cmd netpolicy set restrict-background false
+                        
+                        elif [[ "$optslct" -eq "13" ]]; then
+                        settings put secure location_mode "0"
+                        settings put secure location_providers_allowed ""
+                        
+                        elif [[ "$optslct" -eq "14" ]]; then
+                        settings put secure location_providers_allowed "gps,network"
+                        
+                        elif [[ "$optslct" -eq "15" ]]; then
+                        cleantrash
+
+                        elif [[ "$optslct" -eq "16" ]]; then
+                        am start -a android.intent.action.VIEW -d https://t.me/kingprojectzdiscussion
+                        
+                        elif [[ "$optslct" -eq "17" ]]; then
+                        echo "Copy this link to FKM -> Flasher -> Import a kernel download configuration to always getting alerted when a new KTSR update is released to download!"
+						echo "https://raw.githubusercontent.com/pedrozzz0/King-Tweaks/master/update.json"
+
+						else
+                        usage
+                        fi
+
                         shift $((OPTIND - 1))
                         
 						if [[ -z $kts_pf ]]; then
