Fix device temperature & more indentation changes
Signed-off-by: pedrozzz0 <guitopzika26@gmail.com>

diff --git a/ktsrmenu b/ktsrmenu
--- a/ktsrmenu
+++ b/ktsrmenu
@@ -23,7 +23,7 @@ ls /data >/dev/null 2>&1 || {
 # Magisk Mod Directory
 [[ -d "/sbin/.magisk" ]] && MOUNTPATH="/sbin/.magisk/modules" || MOUNTPATH="$(find /dev -mindepth 2 -maxdepth 2 -type d -name ".magisk")/modules"
 MODDIR="$MOUNTPATH/$ID"
-[[ ! -d "${MODDIR}" ]] && {
+[[ ! -d ${MODDIR} ]] && {
 	echo "[!] Module not detected"
 	exit 1
 }
@@ -62,12 +62,12 @@ set -x 2>"${VERLOG}"
 ktsr_prof=$(getprop persist.king.tweaks.prof)
 
 case "${ktsr_prof}" in
-1) ktsr_prof_en="Automatic" ;;
-2) ktsr_prof_en="Battery" ;;
-3) ktsr_prof_en="Balanced" ;;
-4) ktsr_prof_en="Extreme" ;;
-5) ktsr_prof_en="Gaming" ;;
-6) ktsr_prof_en="Latency" ;;
+	1) ktsr_prof_en="Automatic" ;;
+	2) ktsr_prof_en="Battery" ;;
+	3) ktsr_prof_en="Balanced" ;;
+	4) ktsr_prof_en="Extreme" ;;
+	5) ktsr_prof_en="Gaming" ;;
+	6) ktsr_prof_en="Latency" ;;
 esac
 
 [[ "$(settings get global low_power)" == "1" ]] && low_power_mode="Enabled" || low_power_mode="Disabled"
@@ -102,21 +102,21 @@ menu() {
 	echo ""
 	echo "[7] Optimize apps package"
 	echo ""
-	[[ "${low_power_mode}" == "Disabled" ]] && {
+	[[ ${low_power_mode} == "Disabled" ]] && {
 		echo "[8] Enable low power mode"
 		echo ""
 	} || {
 		echo "[9] Disable low power mode"
 		echo ""
 	}
-	[[ "${data_saver}" == "Disabled" ]] && {
+	[[ ${data_saver} == "Disabled" ]] && {
 		echo "[10] Enable data saver"
 		echo ""
 	} || {
 		echo "[11] Disable data saver"
 		echo ""
 	}
-	[[ "${loc_mode_pwr_saving}" == "Disabled" ]] && {
+	[[ ${loc_mode_pwr_saving} == "Disabled" ]] && {
 		echo "[12] Enable power-saving location mode"
 		echo ""
 	} || {
@@ -170,251 +170,251 @@ menu() {
 	echo -n "${Y}[*] Select the desired option:${N} "
 	read -r option
 	case "${option}" in
-	"1")
-		echo "${B}Applying profile...${N}"
-		setprop persist.king.tweaks.prof "1" 2>/dev/null
-		echo "${G}Done!${N}"
-		sleep 2
-		menu
-		;;
+		"1")
+			echo "${B}Applying profile...${N}"
+			setprop persist.king.tweaks.prof "1" 2>/dev/null
+			echo "${G}Done!${N}"
+			sleep 2
+			menu
+			;;
 
-	"2")
-		echo "${B}Applying profile...${N}"
-		setprop persist.king.tweaks.prof "2" 2>/dev/null
-		echo "${G}Done!"
-		sleep 2
-		menu
-		;;
+		"2")
+			echo "${B}Applying profile...${N}"
+			setprop persist.king.tweaks.prof "2" 2>/dev/null
+			echo "${G}Done!"
+			sleep 2
+			menu
+			;;
 
-	"3")
-		echo "${B}Applying profile...${N}"
-		setprop persist.king.tweaks.prof "3" 2>/dev/null
-		echo "${G}Done!${N}"
-		menu
-		;;
+		"3")
+			echo "${B}Applying profile...${N}"
+			setprop persist.king.tweaks.prof "3" 2>/dev/null
+			echo "${G}Done!${N}"
+			menu
+			;;
 
-	"4")
-		echo "${B}Applying profile...${N}"
-		setprop persist.king.tweaks.prof "4" 2>/dev/null
-		echo "${G}Done!${N}"
-		sleep 2
-		menu
-		;;
+		"4")
+			echo "${B}Applying profile...${N}"
+			setprop persist.king.tweaks.prof "4" 2>/dev/null
+			echo "${G}Done!${N}"
+			sleep 2
+			menu
+			;;
 
-	"5")
-		echo "${B}Applying profile...${N}"
-		setprop persist.king.tweaks.prof "5" 2>/dev/null
-		echo "${G}Done!${N}"
-		sleep 2
-		menu
-		;;
+		"5")
+			echo "${B}Applying profile...${N}"
+			setprop persist.king.tweaks.prof "5" 2>/dev/null
+			echo "${G}Done!${N}"
+			sleep 2
+			menu
+			;;
 
-	"6")
-		echo "${B}Applying profile...${N}"
-		setprop persist.king.tweaks.prof "6" 2>/dev/null
-		echo "${G}Done!${N}"
-		sleep 2
-		menu
-		;;
+		"6")
+			echo "${B}Applying profile...${N}"
+			setprop persist.king.tweaks.prof "6" 2>/dev/null
+			echo "${G}Done!${N}"
+			sleep 2
+			menu
+			;;
 
-	"7")
-		echo "${B}Optimizing packages...${N}"
-		cmd package bg-dexopt-job
-		sleep 5
-		menu
-		;;
+		"7")
+			echo "${B}Optimizing packages...${N}"
+			cmd package bg-dexopt-job
+			sleep 5
+			menu
+			;;
 
-	"8")
-		settings put global low_power 1 2>/dev/null
-		settings put global low_power_sticky 1 2>/dev/null
-		settings put global app_standby_enabled 1 2>/dev/null
-		settings put global forced_app_standby_enabled 1 2>/dev/null
-		settings put global app_auto_restriction_enabled true 2>/dev/null
-		settings put global forced_app_standby_for_small_battery_enabled 1 2>/dev/null
-		echo "${G}Done!${N}"
-		sleep 2
-		menu
-		;;
+		"8")
+			settings put global low_power 1 2>/dev/null
+			settings put global low_power_sticky 1 2>/dev/null
+			settings put global app_standby_enabled 1 2>/dev/null
+			settings put global forced_app_standby_enabled 1 2>/dev/null
+			settings put global app_auto_restriction_enabled true 2>/dev/null
+			settings put global forced_app_standby_for_small_battery_enabled 1 2>/dev/null
+			echo "${G}Done!${N}"
+			sleep 2
+			menu
+			;;
 
-	"9")
-		settings put global low_power 0 2>/dev/null
-		settings reset global low_power 2>/dev/null
-		settings put global low_power_sticky 0 2>/dev/null
-		settings reset global low_power_sticky 2>/dev/null
-		settings put global app_standby_enabled 1 2>/dev/null
-		settings reset global app_standby_enabled 2>/dev/null
-		settings put global forced_app_standby_enabled 0 2>/dev/null
-		settings reset global forced_app_standby_enabled 2>/dev/null
-		settings put global app_auto_restriction_enabled false 2>/dev/null
-		settings reset global app_auto_restriction_enabled 2>/dev/null
-		settings put global forced_app_standby_for_small_battery_enabled 0 2>/dev/null
-		settings reset global forced_app_standby_for_small_battery_enabled 1 2>/dev/null
-		echo "${G}Done!${N}"
-		sleep 2
-		menu
-		;;
+		"9")
+			settings put global low_power 0 2>/dev/null
+			settings reset global low_power 2>/dev/null
+			settings put global low_power_sticky 0 2>/dev/null
+			settings reset global low_power_sticky 2>/dev/null
+			settings put global app_standby_enabled 1 2>/dev/null
+			settings reset global app_standby_enabled 2>/dev/null
+			settings put global forced_app_standby_enabled 0 2>/dev/null
+			settings reset global forced_app_standby_enabled 2>/dev/null
+			settings put global app_auto_restriction_enabled false 2>/dev/null
+			settings reset global app_auto_restriction_enabled 2>/dev/null
+			settings put global forced_app_standby_for_small_battery_enabled 0 2>/dev/null
+			settings reset global forced_app_standby_for_small_battery_enabled 1 2>/dev/null
+			echo "${G}Done!${N}"
+			sleep 2
+			menu
+			;;
 
-	"10")
-		cmd netpolicy set restrict-background true 2>/dev/null
-		echo "${G}Done!${N}"
-		sleep 2
-		menu
-		;;
+		"10")
+			cmd netpolicy set restrict-background true 2>/dev/null
+			echo "${G}Done!${N}"
+			sleep 2
+			menu
+			;;
 
-	"11")
-		cmd netpolicy set restrict-background false 2>/dev/null
-		echo "${G}Done!${N}"
-		sleep 2
-		menu
-		;;
+		"11")
+			cmd netpolicy set restrict-background false 2>/dev/null
+			echo "${G}Done!${N}"
+			sleep 2
+			menu
+			;;
 
-	"12")
-		echo "${B}Applying settings...${N}"
-		settings put secure location_mode "0" 2>/dev/null
-		settings put global assisted_gps_enabled "0" 2>/dev/null
-		echo "${G}Done!${N}"
-		sleep 2
-		menu
-		;;
+		"12")
+			echo "${B}Applying settings...${N}"
+			settings put secure location_mode "0" 2>/dev/null
+			settings put global assisted_gps_enabled "0" 2>/dev/null
+			echo "${G}Done!${N}"
+			sleep 2
+			menu
+			;;
 
-	"13")
-		settings put global assisted_gps_enabled "1" 2>/dev/null
-		echo "${G}Done!${N}"
-		sleep 2
-		menu
-		;;
+		"13")
+			settings put global assisted_gps_enabled "1" 2>/dev/null
+			echo "${G}Done!${N}"
+			sleep 2
+			menu
+			;;
 
-	"14")
-		echo "${B}Cleaning debug logs and system trash...${N}"
-		cleantrash 2>/dev/null
-		echo "${G}Done!${N}"
-		sleep 2
-		menu
-		;;
+		"14")
+			echo "${B}Cleaning debug logs and system trash...${N}"
+			cleantrash 2>/dev/null
+			echo "${G}Done!${N}"
+			sleep 2
+			menu
+			;;
 
-	"15")
-		am start -a android.intent.action.VIEW -d https://t.me/kingprojectzdiscussion
-		menu
-		;;
+		"15")
+			am start -a android.intent.action.VIEW -d https://t.me/kingprojectzdiscussion
+			menu
+			;;
 
-	"16")
-		[[ -e "/sys/module/mdss_mdp/parameters/custom_hz" ]] && [[ "$(grep -Eo '[0-9]' /sys/module/mdss_mdp/parameters/custom_hz 2>/dev/null)" ]] && echo "50" >"/sys/module/mdss_mdp/parameters/custom_hz" || echo "Y" >"/sys/module/mdss_mdp/parameters/custom_hz"
-		echo "${G}Done!${N}"
-		sleep 2
-		menu
-		;;
+		"16")
+			[[ -e "/sys/module/mdss_mdp/parameters/custom_hz" ]] && [[ "$(grep -Eo '[0-9]' /sys/module/mdss_mdp/parameters/custom_hz 2>/dev/null)" ]] && echo "50" >"/sys/module/mdss_mdp/parameters/custom_hz" || echo "Y" >"/sys/module/mdss_mdp/parameters/custom_hz"
+			echo "${G}Done!${N}"
+			sleep 2
+			menu
+			;;
 
-	"17")
-		[[ -e "/sys/module/mdss_mdp/parameters/custom_hz" ]] && [[ "$(grep -Eo '[0-9]' /sys/module/mdss_mdp/parameters/custom_hz 2>/dev/null)" ]] && echo "55" >"/sys/module/mdss_mdp/parameters/custom_hz"
-		echo "${G}Done!${N}"
-		sleep 2
-		menu
-		;;
+		"17")
+			[[ -e "/sys/module/mdss_mdp/parameters/custom_hz" ]] && [[ "$(grep -Eo '[0-9]' /sys/module/mdss_mdp/parameters/custom_hz 2>/dev/null)" ]] && echo "55" >"/sys/module/mdss_mdp/parameters/custom_hz"
+			echo "${G}Done!${N}"
+			sleep 2
+			menu
+			;;
 
-	"18")
-		[[ -e "/sys/module/mdss_mdp/parameters/custom_hz" ]] && [[ "$(grep -o -e '[0-9\.]+' /sys/module/mdss_mdp/parameters/custom_hz 2>/dev/null)" ]] && echo "60" >"/sys/module/mdss_mdp/parameters/custom_hz" || echo "N" >"/sys/module/mdss_mdp/parameters/custom_hz"
-		settings put system min_refresh_rate 60 2>/dev/null
-		settings put system peak_refresh_rate 60 2>/dev/null
-		settings put system user_refresh_rate 60 2>/dev/null
-		settings put global oneplus_screen_refresh_rate 1 2>/dev/null
-		echo "${G}Done!${N}"
-		sleep 2
-		menu
-		;;
+		"18")
+			[[ -e "/sys/module/mdss_mdp/parameters/custom_hz" ]] && [[ "$(grep -o -e '[0-9\.]+' /sys/module/mdss_mdp/parameters/custom_hz 2>/dev/null)" ]] && echo "60" >"/sys/module/mdss_mdp/parameters/custom_hz" || echo "N" >"/sys/module/mdss_mdp/parameters/custom_hz"
+			settings put system min_refresh_rate 60 2>/dev/null
+			settings put system peak_refresh_rate 60 2>/dev/null
+			settings put system user_refresh_rate 60 2>/dev/null
+			settings put global oneplus_screen_refresh_rate 1 2>/dev/null
+			echo "${G}Done!${N}"
+			sleep 2
+			menu
+			;;
 
-	"19")
-		settings put system min_refresh_rate 90 2>/dev/null
-		settings put system peak_refresh_rate 90 2>/dev/null
-		settings put system user_refresh_rate 90 2>/dev/null
-		settings put global oneplus_screen_refresh_rate 0 2>/dev/null
-		echo "${G}Done!${N}"
-		sleep 2
-		menu
-		;;
+		"19")
+			settings put system min_refresh_rate 90 2>/dev/null
+			settings put system peak_refresh_rate 90 2>/dev/null
+			settings put system user_refresh_rate 90 2>/dev/null
+			settings put global oneplus_screen_refresh_rate 0 2>/dev/null
+			echo "${G}Done!${N}"
+			sleep 2
+			menu
+			;;
 
-	"20")
-		settings put system min_refresh_rate 120 2>/dev/null
-		settings put system peak_refresh_rate 120 2>/dev/null
-		settings put system user_refresh_rate 120 2>/dev/null
-		settings put global oneplus_screen_refresh_rate 0 2>/dev/null
-		echo "${G}Done!${N}"
-		sleep 2
-		menu
-		;;
+		"20")
+			settings put system min_refresh_rate 120 2>/dev/null
+			settings put system peak_refresh_rate 120 2>/dev/null
+			settings put system user_refresh_rate 120 2>/dev/null
+			settings put global oneplus_screen_refresh_rate 0 2>/dev/null
+			echo "${G}Done!${N}"
+			sleep 2
+			menu
+			;;
 
-	"21")
-		settings reset system min_refresh_rate >/dev/null 2>&1
-		settings reset system peak_refresh_rate >/dev/null 2>&1
-		settings reset system user_refresh_rate >/dev/null 2>&1
-		settings reset global oneplus_screen_refresh_rate >/dev/null 2>&1
-		echo "${G}Done!${N}"
-		sleep 2
-		menu
-		;;
+		"21")
+			settings reset system min_refresh_rate >/dev/null 2>&1
+			settings reset system peak_refresh_rate >/dev/null 2>&1
+			settings reset system user_refresh_rate >/dev/null 2>&1
+			settings reset global oneplus_screen_refresh_rate >/dev/null 2>&1
+			echo "${G}Done!${N}"
+			sleep 2
+			menu
+			;;
 
-	"22")
-		sync
-		echo "3" >"/proc/sys/vm/drop_caches"
-		echo "${G}Done!${N}"
-		sleep 3
-		menu
-		;;
+		"22")
+			sync
+			echo "3" >"/proc/sys/vm/drop_caches"
+			echo "${G}Done!${N}"
+			sleep 3
+			menu
+			;;
 
-	"23")
-		sync
-		echo "3" >"/proc/sys/vm/drop_caches"
-		am kill-all
-		echo "${G}Done!${N}"
-		sleep 3
-		menu
-		;;
+		"23")
+			sync
+			echo "3" >"/proc/sys/vm/drop_caches"
+			am kill-all
+			echo "${G}Done!${N}"
+			sleep 3
+			menu
+			;;
 
-	"24")
-		sync
-		echo "3" >"/proc/sys/vm/drop_caches"
-		am kill-all
-		sleep 3
-		while IFS= read -r pkg_nm; do
-			[[ "${pkg_nm}" != "com.termux" ]] && [[ "${pkg_nm}" != "jackpal.androidterm" ]] && [[ "${pkg_nm}" != "yarolegovich.materialterminal" ]] && [[ "${pkg_nm}" != "com.google.android.inputmethod.latin" ]] && [[ "${pkg_nm}" != "com.termoneplus" ]] && am force-stop "${pkg_nm}"
-		done <<<"$(pm list packages -e -3 | grep package | cut -f 2 -d ":")"
-		echo "${G}Done!${N}"
-		sleep 2
-		menu
-		;;
+		"24")
+			sync
+			echo "3" >"/proc/sys/vm/drop_caches"
+			am kill-all
+			sleep 3
+			while IFS= read -r pkg_nm; do
+				[[ ${pkg_nm} != "com.termux" ]] && [[ ${pkg_nm} != "jackpal.androidterm" ]] && [[ ${pkg_nm} != "yarolegovich.materialterminal" ]] && [[ ${pkg_nm} != "com.google.android.inputmethod.latin" ]] && [[ ${pkg_nm} != "com.termoneplus" ]] && am force-stop "${pkg_nm}"
+			done <<<"$(pm list packages -e -3 | grep package | cut -f 2 -d ":")"
+			echo "${G}Done!${N}"
+			sleep 2
+			menu
+			;;
 
-	"25")
-		echo "2" >"/sys/class/thermal/thermal_message/sconfig" 2>/dev/null
-		echo "${G}Done!${N}"
-		sleep 2
-		menu
-		;;
+		"25")
+			echo "2" >"/sys/class/thermal/thermal_message/sconfig" 2>/dev/null
+			echo "${G}Done!${N}"
+			sleep 2
+			menu
+			;;
 
-	"26")
-		echo "0" >"/sys/class/thermal/thermal_message/sconfig" 2>/dev/null
-		echo "${G}Done!${N}"
-		sleep 2
-		menu
-		;;
+		"26")
+			echo "0" >"/sys/class/thermal/thermal_message/sconfig" 2>/dev/null
+			echo "${G}Done!${N}"
+			sleep 2
+			menu
+			;;
 
-	"27")
-		rm -rf /data/system/batterystats* 2>/dev/null
-		dumpsys batterystats --reset >/dev/null 2>&1
-		echo "${G}Done!${N}"
-		sleep 2
-		menu
-		;;
+		"27")
+			rm -rf /data/system/batterystats* 2>/dev/null
+			dumpsys batterystats --reset >/dev/null 2>&1
+			echo "${G}Done!${N}"
+			sleep 2
+			menu
+			;;
 
-	"28")
-		am start -a android.intent.action.VIEW -d https://github.com/pedrozzz0/King-Tweaks/wiki/KTW
-		;;
+		"28")
+			am start -a android.intent.action.VIEW -d https://github.com/pedrozzz0/King-Tweaks/wiki/KTW
+			;;
 
-	"0")
-		echo "${G}Hope that see ya soon! ;)${N}"
-		;;
+		"0")
+			echo "${G}Hope that see ya soon! ;)${N}"
+			;;
 
-	*)
-		abort "${R}[!] Unexpected response, aborting...${N}"
-		;;
+		*)
+			abort "${R}[!] Unexpected response, aborting...${N}"
+			;;
 	esac
 }
 
@@ -435,44 +435,44 @@ help_me() {
 
 while getopts ":p:f:th:" opt; do
 	case "${opt}" in
-	p)
-		echo "${B}Applying profile...${N}"
-		setprop persist.king.tweaks.prof "$2" 2>/dev/null
-		echo "${G}Done!${N}"
-		;;
-
-	f)
-		if [[ "$2" == "1" ]]; then
-			sync
-			echo "3" >"/proc/sys/vm/drop_caches"
+		p)
+			echo "${B}Applying profile...${N}"
+			setprop persist.king.tweaks.prof "$2" 2>/dev/null
 			echo "${G}Done!${N}"
-			sleep 2
+			;;
 
-		elif [[ "$2" == "2" ]]; then
-			sync
-			echo "3" >"/proc/sys/vm/drop_caches"
-			am kill-all
-			echo "${G}Done!${N}"
-			sleep 3
+		f)
+			if [[ $2 == "1" ]]; then
+				sync
+				echo "3" >"/proc/sys/vm/drop_caches"
+				echo "${G}Done!${N}"
+				sleep 2
 
-		elif [[ "$2" == "3" ]]; then
-			sync
-			echo "3" >"/proc/sys/vm/drop_caches"
-			am kill-all
-			sleep 3
-			while IFS= read -r pkg_nm; do
-				[[ "${pkg_nm}" != "com.termux" ]] && [[ "${pkg_nm}" != "jackpal.androidterm" ]] && [[ "${pkg_nm}" != "yarolegovich.materialterminal" ]] && [[ "${pkg_nm}" != "com.google.android.inputmethod.latin" ]] && [[ "${pkg_nm}" != "com.termoneplus" ]] && am force-stop "${pkg_nm}"
-			done <<<"$(pm list packages -e -3 | grep package | cut -f 2 -d ":")"
-			echo "${G}Done!${N}"
-			sleep 2
-		else
+			elif [[ $2 == "2" ]]; then
+				sync
+				echo "3" >"/proc/sys/vm/drop_caches"
+				am kill-all
+				echo "${G}Done!${N}"
+				sleep 3
+
+			elif [[ $2 == "3" ]]; then
+				sync
+				echo "3" >"/proc/sys/vm/drop_caches"
+				am kill-all
+				sleep 3
+				while IFS= read -r pkg_nm; do
+					[[ ${pkg_nm} != "com.termux" ]] && [[ ${pkg_nm} != "jackpal.androidterm" ]] && [[ ${pkg_nm} != "yarolegovich.materialterminal" ]] && [[ ${pkg_nm} != "com.google.android.inputmethod.latin" ]] && [[ ${pkg_nm} != "com.termoneplus" ]] && am force-stop "${pkg_nm}"
+				done <<<"$(pm list packages -e -3 | grep package | cut -f 2 -d ":")"
+				echo "${G}Done!${N}"
+				sleep 2
+			else
+				help_me
+			fi
+			;;
+
+		h | *)
 			help_me
-		fi
-		;;
-
-	h | *)
-		help_me
-		;;
+			;;
 	esac
 done
 shift $((OPTIND - 1))
